# .github/workflows/secret-scan.yml
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt credentials and scan stdin
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          rails credentials:show | \
          gitleaks detect --stdin --redact || exit 1
